# This workflow will install Python dependencies, run tests and lint with a variety of Python versions
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate docs

on:
  push:
    branches:
      - dev
      - canary
      - rc
      - master

jobs:
  make_docs:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    - name: Generate docs
      run: |
        python -m pip install --upgrade pip
        cd docs
        python -m pip install -r requirements.txt
        python -m pip install .
        make html
        touch build/html/.nojekyll
    - name: Extract branch name
      shell: bash
      run: |
        echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: Deploy to subdir 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      with:
        branch: gh-pages # The branch the action should deploy to.
        folder: docs/build/html # The folder the action should deploy.
        target-folder: ${{ steps.extract_branch.outputs.branch }}
    - name: Deploy to root 🚀
      uses: JamesIves/github-pages-deploy-action@4.0.0
      if: ${{ steps.extract_branch.outputs.branch == 'master' }}
      with:
        branch: gh-pages
        folder: docs/build/html
        clean-exclude: |
          dev
          canary
          rc
